create table usuario (
	ID_USUARIO INT NOT NULL PRIMARY KEY,
    EH_ADMIN BOOLEAN NOT NULL,
    EMAIL VARCHAR(100),
    LOGIN VARCHAR(50) NOT NULL,
    NOME VARCHAR(60) NOT NULL,
    SENHA VARCHAR(60) NOT NULL,
    TELEFONE VARCHAR(20)
);

create table carrinho (
	ID_USUARIO INT NOT NULL, #FK
	ID_CARRINHO INT NOT NULL PRIMARY KEY,
    
    FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO)
);

create table produto (
	ID_PRODUTO INT NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    NOME VARCHAR(60),
    VLT_UNIT DECIMAL(10, 2)
);

create table estoque (
	ID_ESTOQUE INT NOT NULL PRIMARY KEY,
    ID_PRODUTO INT NOT NULL,
    QNT_PRODUTO INT,
    
	FOREIGN KEY (ID_PRODUTO) REFERENCES produto(ID_PRODUTO)
);

create table produto_X_carrinho (
	ID_USUARIO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    ID_CARRINHO INT NOT NULL,
    QNT_PRODUTO SMALLINT,
    
    FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES produto(ID_PRODUTO)
);

create table venda (
	ID_USUARIO INT NOT NULL,
	ID_VENDA INT NOT NULL PRIMARY KEY,
    ID_CARRINHO INT NOT NULL,
    METODO_PAGAMENTO VARCHAR(3), # BOL - BOLETO
    STATUS VARCHAR(3),
    VLR_TOTAL DECIMAL(10, 2),
    
	FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO),
    FOREIGN KEY (ID_CARRINHO) REFERENCES carrinho(ID_CARRINHO)
);

#create table item_carrinho (
#	ID_USUARIO INT NOT NULL, #FK
#	ID_PRODUTO INT NOT NULL,
#   ID_CARRINHO INT NOT NULL,
#	ID_ITEM_CARRINHO INT NOT NULL PRIMARY KEY,
#   QNT_PRODUTO SMALLINT,
#   FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO),
#   FOREIGN KEY (ID_PRODUTO) REFERENCES produto(ID_PRODUTO)
#);